# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: '25'
          distribution: temurin

      - uses: quarkusio/install-quarkus-snapshots-action@main
        id: quarkus-install

      - uses: quarkusio/install-quarkus-snapshots-action@main
        id: quarkus-install-3-33
        with:
          branch: 3.33

      - uses: quarkusio/install-quarkus-snapshots-action@main
        id: quarkus-install-3-27
        with:
          branch: 3.27


      - name: Verify If Quarkus ${{steps.quarkus-install.outputs.quarkus-version}} are installed
        run: |
          mvn dependency:copy -Dartifact=io.quarkus:quarkus-core:${{steps.quarkus-install.outputs.quarkus-version}} -DoutputDirectory=/tmp/quarkus-verify -DremoteRepositories=local::default::file://${HOME}/.m2/repository
          ls -la /tmp/quarkus-verify/
